package it.introsoft.banker.model.transfer.type;

public enum TransferType {
    DEPOSIT, BANK_DEPOSIT, CHARGES, BANK_CHARGES, INTEREST_TAX_CHARGES, TAX_CHARGES, INSURANCE_CHARGES, CARD_PAYMENT, UNKNOWN_CHARGES, STANDING_ORDER_CHARGES;
}
